export const MCP_TOOLS_CLASS_METADATA = Symbol("MCP_TOOLS_CLASS_METADATA");
export const MCP_TOOL_METADATA = Symbol("MCP_TOOL_METADATA");
export const MCP_TOOL_PARAMS_METADATA = Symbol("MCP_TOOL_PARAMS_METADATA");
